-- =============================================
-- AUTHOR:		NAME
-- CREATE DATE: 
-- DESCRIPTION:	
-- =============================================
CREATE PROCEDURE [DBO].[GETFILEMETADATABYPLAN] 
	-- ADD THE PARAMETERS FOR THE STORED PROCEDURE HERE
	@PLANID VARCHAR(10) = '' 
	
AS
BEGIN
	-- SET NOCOUNT ON ADDED TO PREVENT EXTRA RESULT SETS FROM
	-- INTERFERING WITH SELECT STATEMENTS.
	SET NOCOUNT ON;
	 IF @PLANID <> ''
	   BEGIN 
    SELECT F.ID, F.PLANNAME, DG.ID 'CATEGORYID',DN.ID 'SUBCATEGORYID', DG.NAME 'CATEGORYGROUP', DN.NAME 'SUBCATEGORYNAME', F.FILENAME 'FILENAME', F.DISPLAYNAME 'DISPLAYNAME', FE.NAME 'EXTENSION',FE.ID 'FILEEXTENSIONID',FS.ID 'STATUSID', FS.STATUS, S.SPOSURL, F.STATUSDATE, F.EXPIRATIONDATE, F.ACCESSEDON, F.CREATEDON,
	 F.FILESIZE,FA.ACCESSEDON 'LASTDOWNLOADED',FA.USERID
	 FROM FILEMETADATA F		
		 JOIN CATEGORY DG ON (F.CATEGORYID = DG.ID)
		 JOIN SUBCATEGORY DN ON (F.SUBCATEGORYID=DN.ID)
		 JOIN FILEEXTENSION FE ON (F.FILEEXTENSIONID=FE.ID)
		 JOIN SPOS S ON (F.SPOSID=S.ID)
		 JOIN FILESTATUS FS ON (F.STATUSID= FS.ID)
		 LEFT OUTER JOIN FILEACCESSHISTORY FA ON FA.FILEMETADATAID = F.ID
		 WHERE PLANNAME=@PLANID
		  END
	  ELSE
	  BEGIN
	  SELECT F.ID, F.PLANNAME, DG.ID 'CATEGORYID',DN.ID 'SUBCATEGORYID', DG.NAME 'CATEGORYGROUP', DN.NAME 'SUBCATEGORYNAME', F.FILENAME 'FILENAME', F.DISPLAYNAME 'DISPLAYNAME', FE.NAME 'EXTENSION',FE.ID 'FILEEXTENSIONID',FS.ID 'STATUSID', FS.STATUS, S.SPOSURL, F.STATUSDATE, F.EXPIRATIONDATE, F.ACCESSEDON, F.CREATEDON,
	 F.FILESIZE,FA.ACCESSEDON 'LASTDOWNLOADED',FA.USERID
	 FROM FILEMETADATA F		
		 JOIN CATEGORY DG ON (F.CATEGORYID = DG.ID)
		 JOIN SUBCATEGORY DN ON (F.SUBCATEGORYID=DN.ID)
		 JOIN FILEEXTENSION FE ON (F.FILEEXTENSIONID=FE.ID)
		 JOIN SPOS S ON (F.SPOSID=S.ID)
		 JOIN FILESTATUS FS ON (F.STATUSID= FS.ID)
		 LEFT OUTER JOIN FILEACCESSHISTORY FA ON FA.FILEMETADATAID = F.ID
	  END	
END