CREATE PROCEDURE [DBO].[GETFILEMETADATABYFILTERS]
	-- ADD THE PARAMETERS FOR THE STORED PROCEDURE HERE
	@STATUSID INT = 0,
	@DAYS INT = 0 
	
AS
BEGIN
	-- SET NOCOUNT ON ADDED TO PREVENT EXTRA RESULT SETS FROM
	SET NOCOUNT ON;	  
		 SELECT F.ID, F.PLANNAME, DG.ID 'CATEGORYID',DN.ID 'SUBCATEGORYID', DG.NAME 'CATEGORYGROUP', DN.NAME 'SUBCATEGORYNAME', F.FILENAME 'FILENAME', F.DISPLAYNAME 'DISPLAYNAME', FE.NAME 'EXTENSION',FE.ID 'FILEEXTENSIONID',FS.ID 'STATUSID', FS.STATUS, S.SPOSURL, F.STATUSDATE, F.EXPIRATIONDATE, F.ACCESSEDON, F.CREATEDON,
	 F.FILESIZE,FA.ACCESSEDON 'LASTDOWNLOADED',FA.USERID FROM FILEMETADATA F
		 JOIN CATEGORY DG ON (F.CATEGORYID = DG.ID)
		 JOIN SUBCATEGORY DN ON (F.SUBCATEGORYID=DN.ID)
		 JOIN FILEEXTENSION FE ON (F.FILEEXTENSIONID=FE.ID)
		 JOIN SPOS S ON (F.SPOSID=S.ID)
		 JOIN FILESTATUS FS ON (F.STATUSID= FS.ID)
		 LEFT OUTER JOIN FILEACCESSHISTORY FA ON FA.FILEMETADATAID = F.ID
		 WHERE (@Days > 0 AND F.STATUSID=@STATUSID AND F.EXPIRATIONDATE >= DATEADD(D, @DAYS, GETDATE())) OR (F.STATUSID = @STATUSID)
END